"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import type { PublicTrackingResult } from "@/lib/service-requests";

export function ServiceRequestRecoverForm() {
  const [startedAt, setStartedAt] = useState(() => Date.now()); const [message, setMessage] = useState(""); const [results, setResults] = useState<PublicTrackingResult[]>([]); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage("查詢中..."); setResults([]); const form = new FormData(event.currentTarget); const response = await fetch("/api/service-requests/recover", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), phone: form.get("phone"), website: form.get("website"), startedAt }) }); const data = await response.json(); setResults(data.results ?? []); setMessage(data.ok ? "" : data.message || "目前無法查詢，請稍後再試。"); setStartedAt(Date.now()); setLoading(false); }
  return <div className="mx-auto max-w-3xl"><form onSubmit={submit} className="space-y-6 rounded-[2.5rem] bg-white p-6 shadow-soft md:p-10"><label className="absolute -left-[9999px]" aria-hidden="true">網站<input name="website" tabIndex={-1} autoComplete="off" /></label><label className="block"><span className="font-bold text-forest/75">申請人姓名</span><input name="name" required maxLength={80} className="form-control mt-2" autoComplete="name" /></label><label className="block"><span className="font-bold text-forest/75">申請時填寫的電話</span><input name="phone" required maxLength={30} inputMode="tel" className="form-control mt-2" autoComplete="tel" /></label>{message && <p className="rounded-2xl bg-pink-50 p-4 font-bold text-rose">{message}</p>}<button disabled={loading} className="w-full rounded-full bg-forest px-7 py-4 text-lg font-bold text-white disabled:opacity-50">{loading ? "查詢中..." : "找回案件編號"}</button><p className="text-center text-sm text-forest/55">已有案件編號？<Link href="/track" className="font-bold text-rose underline">查詢案件進度</Link></p></form>{results.length > 0 && <div className="mt-8 space-y-4">{results.map((result) => <article key={result.publicReference} className="rounded-[2rem] bg-white p-6 shadow-soft"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold text-rose">{result.category}</p><h2 className="mt-1 text-2xl font-black text-forest">{result.publicReference}</h2><p className="mt-2 text-sm text-forest/55">建立日期：{new Date(result.createdAt).toLocaleDateString("zh-TW")}</p></div><div className="text-right"><span className="rounded-full bg-blush px-4 py-2 font-bold text-forest">{result.status}</span><Link href="/track" className="mt-4 block font-bold text-rose underline">前往查詢進度</Link></div></div></article>)}</div>}</div>;
}
