-- V1.4: public case tracking and recovery.
create extension if not exists pgcrypto;
alter table service_requests add column if not exists public_reference text, add column if not exists public_reply text not null default '', add column if not exists phone_last4_hash text, add column if not exists phone_lookup_hash text;
create or replace function generate_service_request_reference() returns text language plpgsql as $$ declare alphabet constant text := '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'; candidate text; position integer; begin loop candidate := 'SR-'; for position in 1..6 loop candidate := candidate || substr(alphabet,1+(get_byte(gen_random_bytes(1),0)%length(alphabet)),1); end loop; exit when not exists(select 1 from service_requests where public_reference=candidate); end loop; return candidate; end; $$;
revoke all on function generate_service_request_reference() from public,anon,authenticated; grant execute on function generate_service_request_reference() to service_role;
create or replace function set_service_request_tracking_fields() returns trigger language plpgsql as $$ declare phone_digits text; begin phone_digits:=regexp_replace(coalesce(new.phone,''),'\D','','g'); if new.public_reference is null or new.public_reference='' then new.public_reference:=generate_service_request_reference(); end if; new.phone_lookup_hash:=encode(digest(phone_digits,'sha256'),'hex'); new.phone_last4_hash:=encode(digest(right(phone_digits,4),'sha256'),'hex'); return new; end; $$;
revoke all on function set_service_request_tracking_fields() from public,anon,authenticated; grant execute on function set_service_request_tracking_fields() to service_role;
drop trigger if exists service_requests_set_tracking_fields on service_requests; create trigger service_requests_set_tracking_fields before insert or update of phone,public_reference on service_requests for each row execute function set_service_request_tracking_fields();
update service_requests set public_reference=coalesce(nullif(public_reference,''),generate_service_request_reference()),phone_lookup_hash=encode(digest(regexp_replace(coalesce(phone,''),'\D','','g'),'sha256'),'hex'),phone_last4_hash=encode(digest(right(regexp_replace(coalesce(phone,''),'\D','','g'),4),'sha256'),'hex') where public_reference is null or public_reference='' or phone_lookup_hash is null or phone_last4_hash is null;
alter table service_requests alter column public_reference set not null,alter column phone_last4_hash set not null,alter column phone_lookup_hash set not null;
create unique index if not exists service_requests_public_reference_uidx on service_requests(public_reference); create index if not exists service_requests_recovery_idx on service_requests(phone_lookup_hash,name);
create table if not exists service_request_rate_limits(key_hash text primary key,attempts integer not null default 0,window_started_at timestamptz not null default now(),blocked_until timestamptz,updated_at timestamptz not null default now()); alter table service_request_rate_limits enable row level security;
create or replace function check_service_request_rate_limit(p_key_hash text,p_limit integer default 8,p_window_seconds integer default 900,p_block_seconds integer default 900) returns boolean language plpgsql security definer set search_path=public as $$ declare current_row service_request_rate_limits%rowtype; begin delete from service_request_rate_limits where updated_at<now()-interval '30 days'; insert into service_request_rate_limits(key_hash,attempts) values(p_key_hash,1) on conflict(key_hash) do update set attempts=case when service_request_rate_limits.window_started_at<now()-make_interval(secs=>p_window_seconds) then 1 else service_request_rate_limits.attempts+1 end,window_started_at=case when service_request_rate_limits.window_started_at<now()-make_interval(secs=>p_window_seconds) then now() else service_request_rate_limits.window_started_at end,blocked_until=case when service_request_rate_limits.blocked_until>now() then service_request_rate_limits.blocked_until when service_request_rate_limits.window_started_at>=now()-make_interval(secs=>p_window_seconds) and service_request_rate_limits.attempts+1>p_limit then now()+make_interval(secs=>p_block_seconds) else null end,updated_at=now() returning * into current_row; return current_row.blocked_until is null or current_row.blocked_until<=now(); end; $$;
revoke all on function check_service_request_rate_limit(text,integer,integer,integer) from public,anon,authenticated; grant execute on function check_service_request_rate_limit(text,integer,integer,integer) to service_role;
alter table service_requests enable row level security; revoke all on service_requests from anon,authenticated; revoke all on service_request_rate_limits from anon,authenticated;
